### ISSUE TITLE
Missing osx-64 2.1.0 py35 build

### ISSUE THREAD

**Issue by hajapy** [conda-forge/elasticsearch-dsl-feedstock#2]
There is no osx-64/elasticsearch-dsl-2.1.0-py35_0.tar.bz2 at https://anaconda.org/conda-forge/elasticsearch-dsl. The issue seems to be an uncaught upload failure: https://travis-ci.org/conda-forge/elasticsearch-dsl-feedstock/jobs/148923743#L554

**Comment by pmlandwehr** [comment]
Good catch! Restarting the CI.

**Comment by hajapy** [comment]
Cool, fyi seem to be part of a wider issue: https://github.com/conda-forge/status/issues/4

**Comment by pmlandwehr** [comment]
Yeah - this is a periodic problem. Restarting the CI did nil, though I'll set it off again. Can report upstream as well...

**Comment by hajapy** [comment]
Fixed. Thanks!
